//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Exchange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Exchange()
        {
            this.tb_ExchangeAccountMappping = new HashSet<tb_ExchangeAccountMappping>();
        }
    
        public int n_ExNo { get; set; }
        public string s_ExCode { get; set; }
        public string s_ExName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExchangeAccountMappping> tb_ExchangeAccountMappping { get; set; }
    }
}
