//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Model_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ExchangeAccountMappping
    {
        public int n_ExAccNo { get; set; }
        public string s_ControlAcc { get; set; }
        public int dn_ExNo { get; set; }
    
        public virtual tb_Exchange tb_Exchange { get; set; }
    }
}
